
[profile.deployment]
src = './src'
test = './src'
# allow_paths = ["../dotnugg-v1-core/src"]
sparse_mode = true
sender = '0x9b0e2b16f57648c7baf28edd7772a815af266e77'
optimizer_runs = 10000000
cache = false
force = false
via_ir=true
solc_version = '0.8.17'


[profile.default]
src = 'src'
test = 'test'
out = './out'
libs = ['lib']
cache = true
force = false
evm_version = 'london'
## Sets the concrete solc version to use, this overrides the `auto_detect_solc` value
solc_version = '0.8.17'
auto_detect_solc = false
optimizer = true
optimizer_runs = 10000000
verbosity = 0
ignored_error_codes = []
fuzz_runs = 1000
ffi = true
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 40000000
chain_id = 1
gas_limit = 9223372036854775807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 0
block_difficulty = 0
gas_reports = ["RiggedNuggft", "NuggftV1", "Expect"]


[profile.default.optimizer_details]
constantOptimizer = true
cse = true
deduplicate=true
orderLiterals=true
